apiVersion: v1
kind: Service
metadata:
  name: garage-billing-service
  namespace: default
  labels:
    app: garage-billing-service
spec:
  selector:
    app: garage-billing-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
